# Generated by Django 3.0.7 on 2020-08-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuctionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Zipcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Contact',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='latitiude',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='logitude',
            field=models.TextField(),
        ),
    ]
