# Generated by Django 3.0.7 on 2020-08-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuctionApp', '0002_auto_20200824_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Zipcode',
            field=models.IntegerField(),
        ),
    ]
