# Generated by Django 3.0.7 on 2020-09-09 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuctionApp', '0003_auto_20200824_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='Bid_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 18, 25, 45, 209358)),
        ),
    ]
